### ISSUE TITLE
Site design flowcharts

### ISSUE THREAD

**Issue by andythefan** [Sabriel567/cs373-idb#17]
# Phase 1#

- [ ] flowchart indicating navigation/links between pages
- [ ] graph indicating shared assets/components/styles between pages/templates, etc.
- [ ] list of required dependencies/data per page

**Comment by andythefan** [comment]
# Required data per page#
Pseudo code description of data required to render each page. 

Format:  
> "page.html"
> "type of resource : description of needed data"

## index.html ##
	img : banner stock image
	list : all games (ex. 1864, 1868, ..., 2012)
		for each game:
			str : host country
			img : host country banner
			txt : country fact
			int : total medals won
	list : top 3-5 countries overall
		for each country:
			txt : name
			img: banner 
			Int : total gold medals
			Int : total silver medals
			Int : total bronze medals
	list : top/random 3-5 athletes
		for each athlete:
			txt : athlete name
			txt : origin country 
			img : athlete portrait
			int : total medals won

## games.html ##
	List : all games
	img : host country banner
	Txt : fact about that year
	
	List: top countries that year 
		For each country:
			Int : total medals
			Int : total gold
			Int : total silver
			Int : total bronze
	List : top athletes that year
		For each athlete: 
			Int : total gold
			Int : total silver
			Int : total bronze
			Str : best event
	List : all events that year 
	List : all countries that year 

## countries.html ##
	List : all countries, their regions
	Img : country banner/flag
	Str : country name
	Str : country bio
	Str : country fact
	
	Embed : google map/image of location
	
	List : years country hosted 
		Int : year
	
	List : country's top medalists
	
	List : country's top years
		For each year:
			Int  : year
			Int : total medals 
	
		For each medalist:
			Str : athlete name
			Int : number of gold
			Int : number of silver
			Int : number of bronze
	List : country's top events
		For each event
			Int : total medals for event

## events.html ##
	List : all sports
	List : all events, sports, athletes, countries, year
	List : all events in year
	Str : description of event
	Img : icon of event

## athletes.html ##
	List : all athletes
	Str : name
	Str : origin country
	Str : countries represented
	Str : bio
	
	List : top events
	
	List : games participated
		For each game:
			List : countries represented
			List : events
			List : medals won G/S/B
	Int : total medals
	
## about.html ##
	str : team bio
	list : team members
		For each member:
			img : portrait
			str : bio

## search.html ##
	EVERYTHING????

**Comment by ericsu921** [comment]
I went ahead and added in **[page].html/&lt;id&gt;** to a few of the pages. Because some of these pages may initially show default content such as featured athletes or a timeline for the case of games.html, once an item is selected and the user is brought to [page].html/&lt;id&gt;, the page will then show information more specific to that item. Therefore, [page].html may not have the same content as [page].html/&lt;id&gt;.

**Comment by ericsu921** [comment]
I also added in a **sports.html** page. I thought it made sense to have a page dedicated to the different sports within the olympics, which would be linked to countries, athletes, and events.

**Comment by ericsu921** [comment]
search.html may not be necessary. 

See Issue #68.

**Comment by ericsu921** [comment]
#### Added to index.html
- Featured Sports section
- Stats table for featured athletes

Our most exciting data should be presented on our homepage, index.html, so instead of listing all of our games/sports/athletes/etc., I went ahead and put all our "featured" items on this page. Users can simply click on "All games/sports/athletes/etc." if they want a listing of all those items.

**Comment by ericsu921** [comment]
### Notable Refactoring to Design Flowchart: 
- I placed asterisks (*) by several lists in games.html because I prefer this page to be clean and simple, consisting of a single timeline of all the games. Also, this page is a broad overview of all the games hosted, whereas the lists provided are appropriate on a per-game basis. Perhaps they can be added to games.html/\<id\>
- sports.html now simply shows featured sports followed by a list of all sports.
- sports.html/\<id\> now has links to men's events and women's events, which will redirect you to events.html/\<id\>
- Consider eliminating events.html entirely, or at least have the page present a list of featured events. Since there is such a large number of events, it would be useless to view all of them at once. Each event should be accessed through some other pillar, such as, games or athletes. This is the same reason we present featured athletes in athletes.html instead of presenting all athletes at once.
- events.html/\<id\> now simply shows top medalists followed by a link to all medalists.
- events.html/\<id\>/\<all_medalists\> shows all the medalists who competed at the given event.
- A filter form has been added to athletes.html and countries.html.
- I removed the list of all athletes in countries.html. This pages would be way too long if we listed all the athletes on this page. Instead, there should be a link to countries.html/\<id\>/\<all_athletes\>, which will list all athletes in the given country.
